const siteLanguage={
    "en":{ // English
        "name": "Language: English",
        "flag": "🇬🇧",
        "title": "Lighthouse",
        "greeting": "Hi, [[USER]]!",
        "signUp": "Sign Up",
        "signOut": "Log Out",
        "signIn": "Log In",
        "mySys": "My [[SYSTEM]]",
        "settings": "Settings",
        "myForum": "My Forum",
        "info": "Information",
        "about": "About",
        "tutorial": "Tutorial",
        "glossary": "Glossary",
        "changelog": "Changelog",
        "crisis": "In Crisis?",
        "back": "Go Back",
        "system": "System",
        "tos": "Terms of Service",
        "pp": "Privacy Policy"
    },
    "es":{ // Spanish
        "name": "Idioma: español",
        "flag": "🇪🇸",
        "title": "Faro",
        "greeting": "Hola, [[USER]]!",
        "signUp": "Regístrate",
        "signOut": "Cerrar sesión",
        "signIn": "Iniciar sesión",
        "mySys": "Mi [[SYSTEM]]",
        "settings": "Configuración",
        "myForum": "Foro",
        "info": "Información",
        "about": "Sobre nosotros",
        "tutorial": "Guía",
        "glossary": "Glosario",
        "changelog": "Registro de cambios",
        "crisis": "Intervención en crisis",
        "back": "Volver",
        "system": "Sistema",
        "tos": "Términos de Servicio",
        "pp": "Política de Privacidad"
    },
    "fr":{ // French
        "name": "Langue : Français",
        "flag": "🇫🇷",
        "title": "Phare",
        "greeting": "Salut, [[USER]]!",
        "signUp": "Inscrivez-vous",
        "signOut": "Déconnectez-vous",
        "signIn": "Connectez-vous",
        "mySys": "Mon [[SYSTEM]]",
        "settings": "Paramètres",
        "myForum": "Forum",
        "info": "Informations",
        "about": "À propos de nous",
        "tutorial": "Guider",
        "glossary": "Glossaire",
        "changelog": "Journal des modifications",
        "crisis": "Intervention de crise",
        "back": "Retour",
        "system": "Système",
        "tos": "Conditions d'utilisation",
        "pp": "Politique de confidentialité"
    },
    "de":{ // German
        "name": "Sprache: Deutsch",
        "flag": "🇩🇪",
        "title": "Leuchtturm",
        "greeting": "Hallo, [[USER]]!",
        "signUp": "Melden Sie sich an",
        "signOut": "Melden Sie sich ab",
        "signIn": "Melden Sie sich an",
        "mySys": "Mein [[SYSTEM]]",
        "settings": "Einstellungen",
        "myForum": "Forum",
        "info": "Informationen",
        "about": "Über uns",
        "tutorial": "Leitfaden",
        "glossary": "Glossar",
        "changelog": "Änderungsprotokoll",
        "crisis": "Krisenintervention",
        "back": "Gehen Sie zurück",
        "system": "System",
        "tos": "Nutzungsbedingungen",
        "pp": "Datenschutzrichtlinie"
    },
    "ko":{ // Korean
        "name": "언어: 한국어",
        "flag": "🇰🇷",
        "title": "등대",
        "greeting": "안녕하세요, [[USER]]님!",
        "signUp": "가입",
        "signOut": "로그아웃",
        "signIn": "로그인",
        "mySys": "내 [[SYSTEM]]",
        "settings": "설정",
        "myForum": "포럼",
        "info": "정보",
        "about": "회사 소개",
        "tutorial": "가이드",
        "glossary": "용어집",
        "changelog": "변경내역",
        "crisis": "위기 개입",
        "back": "돌아가기",
        "system": "체계",
        "tos": "서비스 약관",
        "pp": "개인정보 보호정책"
    },
    "pl":{ // Polish
        "name": "Język: polski",
        "flag": "🇵🇱",
        "title": "Latarnia Morska",
        "greeting": "Witaj, [[USER]]!",
        "signUp": "Zarejestruj się",
        "signOut": "Wyloguj się",
        "signIn": "Zaloguj się",
        "mySys": "Mój [[SYSTEM]]",
        "settings": "Ustawienia",
        "myForum": "Forum",
        "info": "Informacje",
        "about": "O nas",
        "tutorial": "Przewodnik",
        "glossary": "Glosariusz",
        "changelog": "Lista zmian",
        "crisis": "Interwencja kryzysowa",
        "back": "Go Back",
        "system": "Wróć",
        "tos": "Regulamin",
        "pp": "Polityka prywatności"
    },
    "fil":{ // Filipino
        "name": "Wika: Filipino",
        "flag": "🇵🇭",
        "title": "Parola",
        "greeting": "Kumusta, [[USER]]!",
        "signUp": "Mag-sign Up",
        "signOut": "Mag-sign Out",
        "signIn": "Mag-sign In",
        "mySys": "Aking [[SYSTEM]]",
        "settings": "Mga Setting",
        "myForum": "Forum",
        "info": "Impormasyon",
        "about": "Tungkol sa amin",
        "tutorial": "Patnubay",
        "glossary": "Talasalitaan",
        "changelog": "Changelog",
        "crisis": "Panghihimasok sa krisis",
        "back": "Bumalik ka",
        "system": "Sistema",
        "tos": "Mga Tuntunin ng Serbisyo",
        "pp": "Patakaran sa Privacy"
    },
    "jp":{ // Japanese
        "name": "言語: 日本語",
        "flag": "🇯🇵",
        "title": "灯台",
        "greeting": "こんにちは、[[USER]]!",
        "signUp": "サインアップ",
        "signOut": "サインアウトする",
        "signIn": "サインイン",
        "mySys": "[[SYSTEM]]",
        "settings": "設定",
        "myForum": "フォーラム",
        "info": "情報",
        "about": "私たちについて",
        "tutorial": "ガイド",
        "glossary": "用語集",
        "changelog": "変更履歴",
        "crisis": "危機介入",
        "back": "ゴーバック",
        "system": "システム",
        "tos": "利用規約",
        "pp": "プライバシーポリシー"
    },
    "uk":{ // Ukranian
        "name": "Мова: українська",
        "flag": "🇺🇦",
        "title": "Маяк",
        "greeting": "Привіт, [[USER]]!",
        "signUp": "Зареєструватися",
        "signOut": "Вихід",
        "signIn": "Увійдіть",
        "mySys": "Моя [[SYSTEM]]",
        "settings": "Налаштування",
        "myForum": "Мій форум",
        "info": "Інформація",
        "about": "Про нас",
        "tutorial": "Як використовувати",
        "glossary": "Глосарій",
        "changelog": "Журнал змін",
        "crisis": "Кризова інтервенція",
        "back": "Попередній",
        "system": "Система",
        "tos": "Умови надання послуг",
        "pp": "Політика конфіденційності"
    },
    "gd":{ // Gaelic, Scotland
        "name": "Cànan: Scots Gaelic",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "title": "Taigh-solais",
        "greeting": "Halo, [[USER]]!",
        "signUp": "Clàradh",
        "signOut": "Clàraich a-mach",
        "signIn": "Clàraich a-steach",
        "mySys": "Mo [[SYSTEM]]",
        "settings": "Suidhichidhean",
        "myForum": "Mo fhòram",
        "info": "Fiosrachadh",
        "about": "Mu thimchioll",
        "tutorial": "Treòir",
        "glossary": "Briathrachas",
        "changelog": "Ùrachaidhean",
        "crisis": "Ann an èiginn slàinte inntinn?",
        "back": "Cùl",
        "system": "Siostam",
        "tos": "Cumhachan seirbheis",
        "pp": "Poileasaidh Dìomhaireachd"
    },
    "ie":{ // Irish
        "name": "Teanga: Gaeilge",
        "flag": "🇮🇪",
        "title": "Tigh Solais",
        "greeting": "Dia dhaoibh, [[USER]]!",
        "signUp": "Cláraigh",
        "signOut": "Logáil Amach",
        "signIn": "Logáil isteach",
        "mySys": "Mo [[SYSTEM]]",
        "settings": "Socruithe",
        "myForum": "Mo fóram",
        "info": "Eolas",
        "about": "Fúinn",
        "tutorial": "Treoir",
        "glossary": "Stór focal",
        "changelog": "Nuashonruithe",
        "crisis": "Idirghabháil Meabhair-Shláinte",
        "back": "Cùl",
        "system": "Córas",
        "tos": "Téarmaí seirbhíse",
        "pp": "Beartas Príobháideachta"
    },
    "it":{ // Italian
        "name": "Lingua: italiano",
        "flag": "🇮🇹",
        "title": "Faro",
        "greeting": "Ciao, [[USER]]!",
        "signUp": "Iscriviti",
        "signOut": "Esci",
        "signIn": "Accedi",
        "mySys": "Mio [[SYSTEM]]",
        "settings": "Impostazioni",
        "myForum": "Mio forum",
        "info": "Informazione",
        "about": "Chi siamo",
        "tutorial": "Tutorial",
        "glossary": "Glossario",
        "changelog": "Log delle modifiche",
        "crisis": "Intervento sulla salute mentale",
        "back": "Indietro",
        "system": "Sistema",
        "tos": "Termini di servizio",
        "pp": "Informativa sulla privacy"
    },
    "eo":{ // Esperanto
        "name": "Lingvo: Esperanto",
        "flag": "🇺🇳", // The actual esperanto flag isn't available.
        "title": "Lumturo",
        "greeting": "Saluton, [[USER]]!",
        "signUp": "Aliĝu",
        "signOut": "Elsaluti",
        "signIn": "Ensalutu",
        "mySys": "Mia [[SYSTEM]]",
        "settings": "Agordoj",
        "myForum": "Mia Forumo",
        "info": "Informoj",
        "about": "Pri ni",
        "tutorial": "Gvidilo",
        "glossary": "Terminaro",
        "changelog": "Ŝanĝprotokolo",
        "crisis": "Kriza interveno",
        "back": "Reiru",
        "system": "Sistemo",
        "tos": "Servokondiĉoj",
        "pp": "Privateca Politiko"
    },
}


exports.siteLanguage = siteLanguage;