const siteLanguage={
    "en":{ // English
        "title": "Lighthouse",
        "greeting": "Hi, [[USER]]!",
        "signUp": "Sign Up",
        "signOut": "Log Out",
        "signIn": "Log In",
        "mySys": "My [[SYSTEM]]",
        "settings": "Settings",
        "myForum": "My Forum",
        "info": "Information",
        "about": "About",
        "tutorial": "Tutorial",
        "glossary": "Glossary",
        "changelog": "Changelog",
        "crisis": "In Crisis?",
        "back": "Go Back",
        "system": "System"
    },
    "es":{ // Spanish
        "title": "Faro",
        "greeting": "Hola, [[USER]]!",
        "signUp": "Regístrate",
        "signOut": "Cerrar sesión",
        "signIn": "Iniciar sesión",
        "mySys": "Mi [[SYSTEM]]",
        "settings": "Configuración",
        "myForum": "Foro",
        "info": "Información",
        "about": "Sobre nosotros",
        "tutorial": "Guía",
        "glossary": "Glosario",
        "changelog": "Registro de cambios",
        "crisis": "Intervención en crisis",
        "back": "Volver",
        "system": "Sistema"
    },
    "fr":{ // French
        "title": "Phare",
        "greeting": "Salut, [[USER]]!",
        "signUp": "Inscrivez-vous",
        "signOut": "Déconnectez-vous",
        "signIn": "Connectez-vous",
        "mySys": "Mon [[SYSTEM]]",
        "settings": "Paramètres",
        "myForum": "Forum",
        "info": "Informations",
        "about": "À propos de nous",
        "tutorial": "Guider",
        "glossary": "Glossaire",
        "changelog": "Journal des modifications",
        "crisis": "Intervention de crise",
        "back": "Retour",
        "system": "Système"
    },
    "de":{ // German
        "title": "Leuchtturm",
        "greeting": "Hallo, [[USER]]!",
        "signUp": "Melden Sie sich an",
        "signOut": "Melden Sie sich ab",
        "signIn": "Melden Sie sich an",
        "mySys": "Mein [[SYSTEM]]",
        "settings": "Einstellungen",
        "myForum": "Forum",
        "info": "Informationen",
        "about": "Über uns",
        "tutorial": "Leitfaden",
        "glossary": "Glossar",
        "changelog": "Änderungsprotokoll",
        "crisis": "Krisenintervention",
        "back": "Gehen Sie zurück",
        "system": "System"
    },
    "ko":{ // Korean
        "title": "등대",
        "greeting": "안녕하세요, [[USER]]님!",
        "signUp": "가입",
        "signOut": "로그아웃",
        "signIn": "로그인",
        "mySys": "내 [[SYSTEM]]",
        "settings": "설정",
        "myForum": "포럼",
        "info": "정보",
        "about": "회사 소개",
        "tutorial": "가이드",
        "glossary": "용어집",
        "changelog": "변경내역",
        "crisis": "위기 개입",
        "back": "돌아가기",
        "system": "체계"
    },
    "pl":{ // Polish
        "title": "Latarnia Morska",
        "greeting": "Witaj, [[USER]]!",
        "signUp": "Zarejestruj się",
        "signOut": "Wyloguj się",
        "signIn": "Zaloguj się",
        "mySys": "Mój [[SYSTEM]]",
        "settings": "Ustawienia",
        "myForum": "Forum",
        "info": "Informacje",
        "about": "O nas",
        "tutorial": "Przewodnik",
        "glossary": "Glosariusz",
        "changelog": "Lista zmian",
        "crisis": "Interwencja kryzysowa",
        "back": "Go Back",
        "system": "Wróć"
    },
    "fil":{ // Filipino
        "title": "Parola",
        "greeting": "Kumusta, [[USER]]!",
        "signUp": "Mag-sign Up",
        "signOut": "Mag-sign Out",
        "signIn": "Mag-sign In",
        "mySys": "Aking [[SYSTEM]]",
        "settings": "Mga Setting",
        "myForum": "Forum",
        "info": "Impormasyon",
        "about": "Tungkol sa amin",
        "tutorial": "Patnubay",
        "glossary": "Talasalitaan",
        "changelog": "Changelog",
        "crisis": "Panghihimasok sa krisis",
        "back": "Bumalik ka",
        "system": "Sistema"
    },
    "jp":{ // Japanese
        "title": "灯台",
        "greeting": "こんにちは、[[USER]]!",
        "signUp": "サインアップ",
        "signOut": "サインアウトする",
        "signIn": "サインイン",
        "mySys": "[[SYSTEM]]",
        "settings": "設定",
        "myForum": "フォーラム",
        "info": "情報",
        "about": "私たちについて",
        "tutorial": "ガイド",
        "glossary": "用語集",
        "changelog": "変更履歴",
        "crisis": "危機介入",
        "back": "ゴーバック",
        "system": "システム"
    },
    "eo":{ // Esperanto
        "title": "Lumturo",
        "greeting": "Saluton, [[USER]]!",
        "signUp": "Aliĝu",
        "signOut": "Elsaluti",
        "signIn": "Ensalutu",
        "mySys": "Mia [[SYSTEM]]",
        "settings": "Agordoj",
        "myForum": "Mia Forumo",
        "info": "Informoj",
        "about": "Pri ni",
        "tutorial": "Gvidilo",
        "glossary": "Terminaro",
        "changelog": "Ŝanĝprotokolo",
        "crisis": "Kriza interveno",
        "back": "Reiru",
        "system": "Sistemo"
    },
}


exports.siteLanguage = siteLanguage;